# Generated by Django 6.0.3 on 2026-04-04 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Loyiha nomi')),
                ('tavsifi', models.TextField(max_length=1000, verbose_name='Loyiha tavsifi')),
                ('yili', models.IntegerField(verbose_name='Bajarilgan yili')),
                ('hudud', models.CharField(max_length=50, verbose_name='Tegishli hudud')),
                ('davlat', models.CharField(max_length=50, verbose_name='Tegishli davlat')),
                ('masul_xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.xodim', verbose_name="Loyiha uchun mas'ul xodim")),
            ],
        ),
    ]
