# Generated by Django 6.0.3 on 2026-04-04 15:22

import about.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavozim', models.CharField(max_length=50, verbose_name='Lavozimi')),
                ('ism', models.CharField(max_length=50, verbose_name='Ismi')),
                ('familiya', models.CharField(max_length=50, verbose_name='Familiya')),
                ('tajriba_yil', models.IntegerField(verbose_name='Tajribasi (yil)')),
            ],
        ),
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_nomer', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('xodim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.xodim', verbose_name=about.models.Xodim)),
            ],
        ),
    ]
